version: '3'

services:
  db:
    image: mongo
    restart: always

  app:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    command: gunicorn --bind 0.0.0.0:5000 autoapp:app
    ports:
      - "5000:5000"

  frontend:
    build:
      context: frontend/
    ports:
      - "8080:8080"


